USERNAME = 'root'
PASSWORD = 'Flp0246802468'
SERVER  = 'Localhost'
DB = 'dados'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "" 